### ISSUE TITLE
[Suggestion] Integration with Blood magic and evil craft

### ISSUE THREAD

**Issue by PriestTheBeast** [TeamLapen/VampirismIntegrations#22]
Integration with Blood magic and Evil craft so all blood is the same.
This might already be possible with crafttweaker, dont know.
Keep up the good work.

**Comment by maxanier** [comment]
There is a Integrations mod which allows you to convert the evil craft/blood magic blood (and more) to Vampirism blood. You will need a blood sieve for that. https://minecraft.curseforge.com/projects/vampirism-integrations/files
Since the blood is used quite differently in those mods I don't want to make all blood types exactly the same

**Comment by maxanier** [comment]
Did not notice you created the issue in this repo, so you already know about the integrations mod :D

Did you try to convert the blood?

**Comment by PriestTheBeast** [comment]
No, i though it was not possible since it was not in the mod description, i made the suggestion without trying in game, sorry my bad, and i agree with what you said 
> Since the blood is used quite differently in those mods I don't want to make all blood types exactly the same

Thx for the reply, keep up the good work
