### ISSUE TITLE
CraftTweaker Support for Vampire Hunter Table

### ISSUE THREAD

**Issue by Hydraheads** [TeamLapen/VampirismIntegrations#27]
If Vampire Hunter exclusive recipes could be set with crafttweaker it would give modpack makers ways to give hunters more unique recipes to have more options in balancing them out. https://github.com/CraftTweaker/CraftTweaker

**Comment by maxanier** [comment]
With Vampirism for MC 1.14 hunter table recipes will be specified in datapacks, so modpack makers should be able to modify the recipes quite easily.

Since 1.12 is slowly coming to an end (at least for Vampirism) and this change would require quite some work and benefit only a few. This will not be added in 1.12. Sorry
