### ISSUE TITLE
Consecration Compat

### ISSUE THREAD

**Issue by tacticalGambling** [TeamLapen/VampirismIntegrations#29]
I believe Consecration would be a very necessary compat. As a mod focusing on vampires, a form of the undead, compat for the mod Consecration is only logical. Obviously, marking all vampires as undead would be something to do, but marking players as the same would be interesting. Also, making holy water affect all undead.

**Comment by maxanier** [comment]
With the latest alpha https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations/files/3125577
consecration integration was added.
All vampire entities are marked as undead and the holy potion will smite any undead creature.
Marking players undead is not possible with Consecration

Currently using fire to smite vampire entities might not work reliably. This will be fixed in Vampirism-1.7 (next alpha)
